### ISSUE TITLE
No get* to assert element is in document

### ISSUE THREAD

**Issue by Meemaw** [Belco90/eslint-plugin-testing-library#28]
I have seen some people started using get* (because it is short) to assert elements are in DOM:

```js
getByText("Text")
```
(note that there is no assignment or anything, just the call)

I would prefer if line was changed to:
```js
expect(queryByText('Text')).toBeInTheDocument()
```

It's longer, but I think we should be explicit in tests on what exactly is being tested. Also, someone new to RTL has no idea get* selectors throw and this is why one can use them to be lazy.

**Comment by thomlom** [comment]
From my point of view, seeing `getByText("text")` in a test to assert an element's presence doesn't shock me though I prefer the readable one. Maybe it's because I'm used to them? I don't know.

While we could create a rule for that, I think it's worth it to discuss it before implementing it. What's your take on this @Belco90?

**Comment by Belco90** [comment]
I like this rule! It seems like a reasonable new rule to me (I even found myself trying to force this before) and should be easy to implement, but it shouldn't be included in the recommended config probably as it's a controversial rule that completely depends on personal opinion about asserting on this way.

I'd go for it with something like `prefer-assert-expect` or something similar, and leave the rule as optional. What do you think @Meemaw ? Do you want to give it a try?

**Comment by thomlom** [comment]
Completely agree with you @Belco90 🙂

**Comment by emmenko** [comment]
I'm wondering if this is more of a rule for the async behavior 🤔

For instance, I would expect to do something like `await waitForElement(() => getByText("Text"))`.

Assuming that you meant to do `expect(queryByText('Text').toBeInTheDocument()` might be a bit too opinionated.

Thoughts?

**Comment by Belco90** [comment]
Not really related to async behavior.

For this one
`await waitForElement(() => getByText("Text"))`
The rule should not complain, as it's waiting for that get for doing something else after.

The rule shouldn't aim to autofix it to `expect(queryByText('Text').toBeInTheDocument()`anyway (this should be the ideal assert, but there are few others alternatives), it would only complain about having a `getByText("Text")` call used as an assert and recommend to wrap it within an `expect` operator.

**Comment by Belco90** [comment]
(I have updated my rule name suggestion for clarification)

**Comment by emmenko** [comment]
Ok yeah, so it should recommend to either await for it or to wrap it in an expect (which then the other rule kicks in to use `queryBy`). Did I get it right?

**Comment by Meemaw** [comment]
I like the name `no-get-by-assert` 👍 I can give it a try in weekend, but fell free to implement it before if you have some spare time.

**Comment by Belco90** [comment]
@Meemaw I was inspired this evening and got quick implementation for this rule. Let me know what you think.

**Comment by Belco90** [comment]
@all-contributors please add @Meemaw for ideas
