### ISSUE TITLE
Code coverage improvements

### ISSUE THREAD

**Issue by Belco90** [Belco90/eslint-plugin-testing-library#36]
Now that we have 100% coverage in the repo, it would be nice to set proper coverage threshold and check it on corresponding PRs.

For accomplishing this we would have to:

- set coverage threshold to 100%
- add necessary script to execute the tests in coverage mode
- execute the coverage mode in the CI
- prevent PRs to be merged in coverage has been decreased

**Comment by thomlom** [comment]
Will do it 🙂
