### ISSUE TITLE
prefer-explicit-assert does not work as expected

### ISSUE THREAD

**Issue by Meemaw** [Belco90/eslint-plugin-testing-library#40]
![Screen Shot 2019-10-31 at 4 28 35 PM](https://user-images.githubusercontent.com/8524109/67961108-8d730800-fbfb-11e9-8f43-f5af70067a5b.png)

**Comment by thomlom** [comment]
If I get it right, the thing is when you destructure queries statement such as `getByText` from `render`, the rule throws while it shouldn't.

I'll take a look at this.

**Comment by afontcu** [comment]
I just wanted to confirm that I'm also getting linting errors on destructuring lines 👍
