### ISSUE TITLE
Prefer explicit assert should check if node property is accessed

### ISSUE THREAD

**Issue by Meemaw** [Belco90/eslint-plugin-testing-library#45]
In my opinion the following snippet should not raise a linting error (I know that this could be avoided by extracting it into a a temp variable).

![Screen Shot 2019-11-11 at 11 08 48 AM](https://user-images.githubusercontent.com/8524109/68579148-bef99800-0473-11ea-9021-d6a5400d2fe3.png)

**Comment by thomlom** [comment]
Indeed. I'll investigate this issue and will get back to you on this 🙂

**Comment by Belco90** [comment]
Interesting bug. I'll try to take a look at it this week as I'm back from holidays!

**Comment by Belco90** [comment]
Also, this bug makes me think about if we can have more issues like this one in other rules, as @thomlom mentioned to me it would be a good idea to implement more "realistic" tests to cover this kind of edge cases.

**Comment by Belco90** [comment]
I hope I can go back to this in Christmas when I have some spare time. Sorry!
